/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2 SP1
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "TPS_ADC.h"
#include "TPS_0_aliases.h"
#include "TPS_0.h"
#include "TPS_1_aliases.h"
#include "TPS_1.h"
#include "TPS_2_aliases.h"
#include "TPS_2.h"
#include "APPS_ADC.h"
#include "APPS_1_aliases.h"
#include "APPS_1.h"
#include "APPS_2_aliases.h"
#include "APPS_2.h"
#include "APPS_3_aliases.h"
#include "APPS_3.h"
#include "TPS_ADC_SAR.h"
#include "TPS_ADC_IntClock.h"
#include "TPS_ADC_TempBuf_dma.h"
#include "TPS_ADC_FinalBuf_dma.h"
#include "TPS_ADC_IRQ.h"
#include "APPS_ADC_SAR.h"
#include "APPS_ADC_IntClock.h"
#include "APPS_ADC_TempBuf_dma.h"
#include "APPS_ADC_FinalBuf_dma.h"
#include "APPS_ADC_IRQ.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

