/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2 SP1
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_RedLED.h"
#include "Pin_RedLED_aliases.h"
#include "Pin_GreenLED.h"
#include "Pin_GreenLED_aliases.h"
#include "Pin_BlueLED.h"
#include "Pin_BlueLED_aliases.h"
#include "Clock_PWM.h"
#include "PWM_R.h"
#include "PWM_G.h"
#include "PWM_B.h"
#include "CapSense_1.h"
#include "CapSense_1_CSHL.h"
#include "CapSense_1_TunerHelper.h"
#include "CapSense_1_PVT.h"
#include "CapSense_1_IP.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "CapSense_1_SampleClk.h"
#include "CapSense_1_Sns_aliases.h"
#include "CapSense_1_SenseClk.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

