/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2 SP1
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED.h"
#include "LED_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "Input_4.h"
#include "Input_4_aliases.h"
#include "Input_3.h"
#include "Input_3_aliases.h"
#include "Differential_In_2.h"
#include "Differential_In_2_aliases.h"
#include "Differential_In_1.h"
#include "Differential_In_1_aliases.h"
#include "Out_2.h"
#include "Out_2_aliases.h"
#include "Out_1.h"
#include "Out_1_aliases.h"
#include "Preamp_In_2.h"
#include "Preamp_In_2_aliases.h"
#include "Inv_2.h"
#include "Inv_2_aliases.h"
#include "Inv_1.h"
#include "Inv_1_aliases.h"
#include "Preamp_In_1.h"
#include "Preamp_In_1_aliases.h"
#include "Opamp_2.h"
#include "ADC.h"
#include "Opamp_1.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

