/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Service Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <PAN.h>
#include <TILT.h>
#include <H100.h>
#include <PAN_O.h>
#include <PAN_O_aliases.h>
#include <TILT_O.h>
#include <TILT_O_aliases.h>
#include <I2CM.h>
#include <I2CM_I2C.h>
#include <I2CM_PINS.h>
#include <I2CM_I2C_PVT.h>
#include <I2CM_PVT.h>
#include <RESET.h>
#include <RESET_aliases.h>
#include <CLOCK.h>
#include <CLOCK_aliases.h>
#include <I2CM_SCB_IRQ.h>
#include <I2CM_SCBCLK.h>
#include <I2CM_scl.h>
#include <I2CM_scl_aliases.h>
#include <I2CM_sda.h>
#include <I2CM_sda_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>

/*[]*/

